# Generated by Django 2.1.5 on 2019-02-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190221_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('family', models.CharField(max_length=256)),
                ('job', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhonesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobilePhoneNo', models.CharField(max_length=20)),
                ('IsInWhatsapp', models.BooleanField()),
                ('IsInTelegram', models.BooleanField()),
                ('IsInInstagram', models.BooleanField()),
                ('sHomePhoneNo', models.CharField(max_length=20)),
                ('sWorkPhoneNo', models.CharField(max_length=20)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ContactsTable')),
            ],
        ),
        migrations.RemoveField(
            model_name='phonenumbers',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='PhoneNumbers',
        ),
    ]
