# Generated by Django 2.1.5 on 2019-04-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190221_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonestable',
            name='IsInWhatsapp',
            field=models.BooleanField(null=True),
        ),
    ]
