# Generated by Django 2.1.5 on 2019-05-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190429_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonestable',
            name='IsInInstagram',
        ),
        migrations.AlterField(
            model_name='phonestable',
            name='IsInTelegram',
            field=models.BooleanField(null=True),
        ),
    ]
